### ISSUE TITLE
Fails to compile on POSIX systems

### ISSUE THREAD

**Issue by AntonioArtigas** [BindBC/bindbc-openal#2]
On POSIX/Linux, the library fails to compile because of these [lines](https://github.com/BindBC/bindbc-openal/blob/8d9a6ba9993a86067accd7d1cc7ea52aab7a095a/source/bindbc/openal/binddynamic.d#L237-L240). This PR #1 should fix it.

**Comment by mdparker** [comment]
Thanks. I had no idea that PR was there.
